# -*- coding: utf-8 -*-
"""Homework1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/117t-wypET_PHNWpTHLNB7VBmcVpxhsuO

## 1. Create 2 dataframes for each of the files. So to read the excel files:
"""

import pandas as pd

df1 = pd. read_excel("dataframe1.xlsx")
df2= pd. read_excel("dataframe2.xlsx")

"""##2. Join both files into a single data frame."""

df_joined = df1.merge(df2, left_on ='Student ID', 
                       right_on = 'Student ID',
                       how = 'right')

"""##3. Get the name of the students with maximum grades for each midterm, final and projects.

###To do that, i will use a pandas function called idxmax. Idmax; Return index of first occurrence of maximum over requested axis. By this function we can get any value about the person who got the maximum grade at Midterm exam.
"""

print(df_joined.loc[df_joined['Midterm'] .idxmax() ] ['Name'])

print(df_joined.loc[df_joined['Final'] .idxmax() ] ['Name'])

print(df_joined.loc[df_joined['Project Grades'] .idxmax() ] ['Name'])

"""##4. Find the average, maximum and minimum grades for midterm, final and projects."""

print(df_joined['Midterm'] .agg(["mean","max","min"]))

print(df_joined['Final'].agg( ['mean', 'min', 'max']))

print(df_joined['Project Grades'].agg( ['mean', 'min', 'max']))

"""##5. Normalize all grades with min-max normalization.
### When i tried to normalize everything i got an error says could not convert string to float: 'Ecem', so we need to remove strings, also i dont want to normalize the Student ID's.
"""

from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
without_name_df = df_joined.drop ('Name', axis = 1)
without_name_and_id_df = without_name_df.drop ('Student ID', axis = 1)
df_new = mms.fit_transform(without_name_and_id_df)

"""##6. Sort the dataframe by the name of students lexiconically."""

sorted_df= df_joined.sort_values(by='Name')
print(sorted_df)